### ISSUE TITLE
Choppy Animation when Android version < 4.4 (with suggested solution)

### ISSUE THREAD

**Issue by fungnoth** [adchsm/Slidebars#104]
I took a look of slidebars.js and found that when user is running Android 4.3 or below, it use "side" as the animation style.
That makes the animation really choppy. I've even tested it on my laptop. A laptop with Sandy Bridge i7 won't perform that well too.

CSS translate only fail when slidebar's position is fixed.
Would you please make it CSS translate when sb-static is on?
And probably tell others it will be choppy on Android 4.3 or below when it's fixed position

Thanks
(Maybe that sounds a little impolite to you. Sorry about that. I am not native English speaker. I don't know which word is the best choice.

**Comment by adchsm** [comment]
Hi there,

The new Slidebars only offers CSS transitions so this shouldn't be a problem soon :)

Thanks,

Adam
