### ISSUE TITLE
TypeError: object is not a function when $.slidebars() called in AngularJS controller

### ISSUE THREAD

**Issue by ghost** [adchsm/Slidebars#107]
Hi,

I've been using version 0.9.4 for a while inside an angular controller like so:

``` javascript
app.controller('HomeCtrl', ['$scope', function ($scope) {
    $.slidebars();
}]);
```

And it worked well. But when I tried to update to version 0.10 (mainly to use the ScrollLock functionality), I now get an error:

``` javascript
TypeError: object is not a function
```

Any idea why that would be?

**Comment by mrhirenmodi** [comment]
It's still having error in plunker example.
