### ISSUE TITLE
css background-attachment:fixed not working

### ISSUE THREAD

**Issue by zoo-loop** [adchsm/Slidebars#11]
The background doesn't stay fixed to the element, it performs as if background-attachment:scroll.

**Comment by LenWright** [comment]
I was having the same problem and was about to give up, and this post solved my issue. Thanks!

**Comment by zhrance** [comment]
This fix works wonderful for Chrome, but doesn't do the job for iOS. Searching around now for hours. Still didn't found a solution. Would love to hear from you guys if you have the same issue? Or maybe even a solution! :)
