### ISSUE TITLE
slidebars.active() doesnt return true

### ISSUE THREAD

**Issue by ThaDNA** [adchsm/Slidebars#136]
I want initialise some code after de sidebar has opened.
However when I use .active, it returns false, even when I open the sidebar.

My code:

    var myslidebar = new $.slidebars();

	$('#menu-btn').on('click', function(event) {
		if(myslidebar.slidebars.active('right')){
			alert();
		}
	});

This should work right?

**Comment by adchsm** [comment]
I have changed this on the new dev version of Slidebars so the active variable is switched on instantly, so this should fix this problem :)
