### ISSUE TITLE
Window Resize and Initializing Slidebars

### ISSUE THREAD

**Issue by christopherdro** [adchsm/Slidebars#139]
Hey,

I'm trying to implement  Slidebars on devices with a width of 992 or lower.

Im using enquire.js to handle my media queries and I'm having after getting the first initial trigger from the media query.

I use $.slidebars.close(); to make sure the left-side closes when the user switches from lets say portrait to landscape.

However, if you resize the window again afterwards, either bigger or smaller by even 1px it bring slidebars back and adds all the classes (.sb-active-left, .sb-init, etc..) back to the html tag. 

Note: This resize i'm talking about has to with physically resizing a desktop browser.

leftActive gets correctly set to false when i use $.slidebars.close(); but then upon the resize it returns true and brings back slidebars.

What would be the best way to achieve having slidebars active only at a certain breakpoints?

Thanks.

**Comment by jonny-harte** [comment]
Hi, is this still the way to disable slidebars on desktop?

**Comment by JoryHogeveen** [comment]
@hartey11 Nope, see: https://www.adchsm.com/slidebars/help/advanced-usage/disabling-slidebars/

**Comment by jonny-harte** [comment]
Hey @JoryHogeveen I've tried this but I keep getting "Uncaught Slidebars hasn't been initialized" When resizing the browser. Any idea how to stop this?

Looks like it might be related to this issue.
https://github.com/adchsm/Slidebars/issues/274

**Comment by JoryHogeveen** [comment]
Can you share your code on how you have set up Slidebars?

**Comment by jonny-harte** [comment]
Sure:

```
function breakpoint() {
  const tablet_small = window.matchMedia('(min-width: 37.5rem)'),
    tablet_medium = window.matchMedia('(min-width: 50rem)'),
    desktop = window.matchMedia('(min-width: 64.0625rem)');

  if (!desktop.matches && !tablet_medium.matches && !tablet_small.matches) {
    return 'mobile';
  } else if (!desktop.matches && !tablet_medium.matches) {
    return 'tablet-small';
  } else if (!desktop.matches) {
    return 'tablet-medium';
  } else {
    return 'desktop';
  }
}

const controller = new slidebars();

    // Enable/Disable Slidebars
    const enableSlidebars = function () {
      if ($.inArray(breakpoint(), ['mobile', 'tablet-small', 'tablet-medium']) > -1 && !controller.isActive()) {
        controller.init(function () {
          console.log('Slidebars has been enabled.');
        });
      } else if ($.inArray(breakpoint(), ['desktop']) > -1 && controller.isActive()) {
        controller.exit(function () {
          console.log('Slidebars has been disabled.');
        });
      }
    };
```

**Comment by JoryHogeveen** [comment]
Looks fine to me. You are still getting errors with this code I even though you are using `isActive()`?

**Comment by jonny-harte** [comment]
Yeah. here's a link to the site. When you resize page the breakpoint at 1025px you get the error
https://seerene.harte.onine

**Comment by JoryHogeveen** [comment]
Hi @hartey11 The link isnt working for me. `DNS_PROBE_FINISHED_NXDOMAIN`
