### ISSUE TITLE
More clicks are needed in IE8

### ISSUE THREAD

**Issue by asketatriod** [adchsm/Slidebars#143]
Hello,

Your library works well in IE8 but when I click on the toggle button the slidebar doesn't reveal. The button needs to be clicked more than once. It happens just to the right button when you clicked the left button before (especially when you closed the left slidebar by clicking to the main content).

This can be reproduced simply by copying the example, putting toggle buttons and running in IE with IE8 emulation. (e.g. slidebars.azurewebsites.net)

Thank you,
Michal

**Comment by adchsm** [comment]
Hey Michal,

I'm sorry to say I won't be fixing this. I've developed a new version of Slidebars which has dropped support for IE 8.

Thanks,

Adam
