### ISSUE TITLE
Overlay layer with opacity over sb-site?

### ISSUE THREAD

**Issue by estebandinamarca** [adchsm/Slidebars#154]
Simple question:
Is it possible to add an overlay layer over "sb-site" when slidebar is open?

Example here (please click on "shoping bag", on top-right of the screen):

http://store.moleskine.com/gbr/en-gb

**Comment by yukihariguchi** [comment]
Is it possible to add an overlay layer over "sb-site" when slidebar is open if navigation bar(ex: header) is fixed?

**Comment by berlindave** [comment]
Unfortunately Slidebars 2 doesn't seem to add this extra class to the html anymore. Is there still a similar solution for this question?

**Comment by JoryHogeveen** [comment]
This can be done in JavaScript.
There are various events available to add and remove your own class: https://www.adchsm.com/slidebars/help/events/
