### ISSUE TITLE
scrollLock is not working. (And I have two scrollbars)

### ISSUE THREAD

**Issue by 97gupe30** [adchsm/Slidebars#160]
Hi there! I can't get scrollLock to work. I have this in jquery: 

$(document).ready(function() {
    (function($) {
    $(document).ready(function() {
      $.slidebars({
          scrollLock: false
      });
    });
  }) (jQuery);

I tried to do "siteClose: true" and that works but I can't get scrollLock to work, even if I add it I can still scroll. Im I retarded here or is this a bug?

I also noticed that I have a problem with a double scroll bar.

EDIT: I am also using the newest version.
EDIT: I got the scrollLock working by switching to version 10.0.1 so I guess it's something wrong with v 10.0.2. I still got the problem with two scrollbars though,

**Comment by szyam** [comment]
@97gupe30 You can definitely use in WP. WP is really no different from a standard php site, you can usually use any css or jquery you like.

**Comment by adchsm** [comment]
Yep as @szyam said, its definately possible in WordPress.

For example, you'll want to add the scripts and styles using [wp_enqueue_scripts](http://codex.wordpress.org/Plugin_API/Action_Reference/wp_enqueue_scripts).

Then, you might want your opening `sb-site` div in `header.php` and the closing tag for this in `footer.php`. Also in `footer.php` you may want your Slidebars markup `<div class="sb-slidebar sb-left">` etc.

You could then add content to the Slidebars by adding [menus](http://codex.wordpress.org/Function_Reference/register_nav_menus) and [widgetized sidebars](http://codex.wordpress.org/Function_Reference/register_sidebar).

I hope that helps,

Thanks, Adam
