### ISSUE TITLE
3 seconds delay when opening in chrome on Android 

### ISSUE THREAD

**Issue by SimonMayerhofer** [adchsm/Slidebars#161]
I have a 3 seconds delay when I want to open the slidebar in chrome 39.0.2171.93
I use Android 4.4.4

here is the page where the problem appears: http://www.kwk.artfulsolutions.de/

In all other browser it is woking. Only in chrome it doesn't.

When I try to close I don't have this problem.

**Comment by adchsm** [comment]
Hi there, thats a strange one.

Your markup looks all ok, and I dont seem to have this problem on the Slidebars website on Chrome and Android.

Theres two things I can see initially.

1) You seem to be including jQuery twice, once from a local source and once from Google.
2) This script seems to be catching click events which might have something to do with it (in main.js).

```javscript
$(document).on('click', function(event) {
  if (!$(event.target).closest('#sb-search').length) {
    $('#sb-search').removeClass('sb-search-open');
    $('#header_logo_wrapper').removeClass('search_open');
    $('#header_menu_wrapper').removeClass('search_open');
  }
}); 
```

What happens if you remove that?

Thanks, Adam

**Comment by SimonMayerhofer** [comment]
I also have no problems on the Slidebars website. Even on other Androids I have. It happens only on 1 device (Oneplus One).

1) Thanks, forgot to remove the local source.
2) I tried to remove all of my own js but it still happens.

**Comment by adchsm** [comment]
Hmm that's really strange. I'm afraid I can't really help you much more at the moment. I'm not currently developing Slidebars and I don't have a physical Android device to test on. I'll leave this open here though, someone might be able to give an insight into whats happening.

Thanks, Adam

**Comment by SimonMayerhofer** [comment]
Hay, no problem. It's only not working on exactly 1 device I know. So it might be a problem of it.
Thanks anyway :)

**Comment by SimonMayerhofer** [comment]
Okay, it seems that it's not a problem of slidebars. Because when I add a `.toggle()` command to another element the same issue appears. So I'm going to close this.

**Comment by adchsm** [comment]
That's great you found the problem, thanks for letting me know.
