### ISSUE TITLE
Navbar covering scrollbar

### ISSUE THREAD

**Issue by christraverse** [adchsm/Slidebars#166]
I've got a fixed navbar that is outside of the #sb-slide element, but instead of the navbar appearing to the side of the navbar, as should happen, the navbar is extending over the top of the scrollbar.  Im also getting a gap to the right of elements in s-vsite when the right slidebar is opened.  Its the same size as the scrollbar would be if it were there.  The scrollLock doesn't seem to be working either but that's much less of an issue.  Im using the latest versions of the css and js.

Here's a link so you can see what I mean http://jctrl-dev.azurewebsites.net/

(the left toggle is the hamburger menu and the right toggle is the cart icon)

**Comment by adchsm** [comment]
Hi christraverse,

I'm not quite sure what the problems are. Your navbar seems to be the correct width, and there doesn't seem to be any strange spacing when the right Slidebar is open. What OS/browser are you using?

Thanks, Adam

**Comment by christraverse** [comment]
It's Windows7 / Chrome.  

But I've just figured it out.  There is a <style> tag on the index page I thought I'd removed that had position:absolute; in it and removing that has cleared all of the issues except for the scrollLock not working, which like I said isn't a big issue for me.

**Comment by adchsm** [comment]
Great to hear you got it sorted. `There are issues with scrollLock, and there is an issue raised [here](https://github.com/adchsm/Slidebars/issues/131) about it. I'm not currently developing Slidebars at the moment, so there wont be a fix anytime soon I'm afraid.

**Comment by cleor41** [comment]
For anyone who still has this issue, I had an issue with this when I used it in conjunction with the bootstrap navbar fixed top. I changed the position from fixed to absolute and it stopped covering the scroll bar.
