### ISSUE TITLE
Bind function to siteClose

### ISSUE THREAD

**Issue by madsdonkin** [adchsm/Slidebars#167]
Thank you for a really great plugin!

Is it possible to bind a js function to the site close event?

**Comment by adchsm** [comment]
Yeah if you define your own instance of Slidebars when initiating the plugin, there are a few methods you can call.

```js
var yourVariable = new $.slidebars();

// You can then use:
// yourVariable.slidebars.close();
// to close the site.

$( something ).on( something, function() {
    yourVariable.slidebars.close();
} );
```

For a complete list, check out the [API page](http://plugins.adchsm.me/slidebars/usage.php#api).

I hope that helps,

Thanks, Adam

**Comment by madsdonkin** [comment]
Thank you so much Adam!

**Comment by adchsm** [comment]
Sorry I think I completely misread your question.

There was dev version with callbacks and events in the works, but I've abandoned it as the whole plugin needs reworking. At the moment there I'm not developing it, but I will do at some point this year.

You could use the method above though have control over the closes and then launch your own methods too.

**Comment by madsdonkin** [comment]
That's okay ;)

i've just added the code to the open and close functions in the sidebars.js and the minified it myself!
