### ISSUE TITLE
Sidebar left sb-toogle-left - Android < 4.3

### ISSUE THREAD

**Issue by marc60** [adchsm/Slidebars#168]
Hi,

at first, great work. 

Maybe the problem is similiar to this one:

https://github.com/adchsm/Slidebars/issues/129

but I am not sure.

Problem happends only in Android < 4.3 with default browser and dolphin:

1. Click the sb-toogle-left menu button.
2. Left sidebar is opening.
3. The first a href link in the sidebar-left is hovering. (its not nice but its no problem for me)
4. Click on the sb-toogle-left menu button again.

Now your script is hitting every a href or onclick (tested both) from the navbar. In my case the logo.  href="/"> - When hitting its opening the startside. 
When I remove for testing issues the href="/" its opening the right sidebar.

This happends on your website also:

http://plugins.adchsm.me/slidebars/

When you are already on the startside http://plugins.adchsm.me/ its ok because the link is already href="/"

Note: When you click on the content and NOT the sb-toogle-left to close the menu, everything is ok. I use the latest version 10.2. It happends also with the developer version.

I know you are busy with other projects but I hope you have a fix for this. 
thanks for help

**Comment by adchsm** [comment]
Hi Marc,

Thanks for letting me know.

Unfortunately there will be no fixes for this anytime soon, I'm not likely to even look at the plugin for a few months yet.

I'm sorry I can't be of any more help,

Thanks, Adam

**Comment by marc60** [comment]
Hi,

Thanks for your quick reply. I fully understand that the day have only 24 hours and my time is always to less. Many projects, 2 kids etc.  But atleast its a matter of priority. I understand when you dont want to give any more priority to this project.  I can hire someone else but I am not sure they make it as good as you because you are the founder.  Is it possible to hire you? I have a very good budget. Just tell me your price and the time you need and I will send it via paypal. For me is this problem very important because I have many users with Android < 4.3. 

Just letting me know and I will send you a email.

**Comment by marc60** [comment]
When this is not possible. I will build me a workarround. When Android < 4.3 hide the toogle button when the left sidebar is open.
I know how to detect the the Android version and to hide (display:none) the menu botton but I dont know how to detect if the sidebar is open.

Is there something like:

If sidebar-is-open
{


}

thank you

**Comment by marc60** [comment]
ok, found it self

if (leftActive)

I have now a nice workarround now. When Android < 4.3 the toogle button is hidding when the left menu is open. In the left menu is showing a close link with sb-close only for android < 4.3

When someone would like to know how this is done, I can give you a easy tutorial.

**Comment by adchsm** [comment]
Glad to hear you found a work around :)

**Comment by marc60** [comment]
here my workarround. Maybe someone need or myself need it anytime. When switching from code to got I forget always what I did last week ;)

Maybe its quick and dirty but it works perfect for me.

1. css:

.workarround{font-weight:bold;font-style:italic;}


2. open Slidebars-0.10.2\distribution\0.10.2\slidebars.js
Its easier to edit. We minify it later again

3 find: setTimeout(function() { leftActive = true; }, 400); // Set active variables.

copy and paste after:

var ua = navigator.userAgent;
if( ua.indexOf("Android") >= 0 )
{
  var androidversion = parseFloat(ua.slice(ua.indexOf("Android")+8)); 
}
if ((androidversion < 4.3) || (navigator.userAgent.match(/dolphin/i)))
{
//we hide the button when the sidebar is open

$('.navicon-line').css({'opacity':'0'});
$('.workarround').css({'display':'block'});
} else {
$('.workarround').css({'display':'none'});
}

4. find if (leftActive || rightActive) { // If a Slidebar is open.
				if (leftActive) {

copy and paste after:

//we show the button again when the sitebar is closed

$('.navicon-line').css({'opacity':'1'});


5. open sidebar_left.html

As first LI point add:

<li class="sb-close workarround"><a href="javascript:void(0);"><span class="mobileclosetext"></span></a></li>

with this code we give the android < 4.3 users a easy link to close the menu because they cant see the menu button

6. Sometimes it happends that the first link or onclick in the sidebar-left is hovering and click it self the first link. In this case it would be our workarround link. But there is the sb-close. That means sidebar opens and close again. To prevent this add in the top image of the sidebar-left:

onclick="document.location.href='javascript:void(0)'; return false;"


7. Done.

Like I said, from a procoder this is maybe quick and dirty but for a workarround its ok :)

**Comment by adchsm** [comment]
Hey,

I've been working on a new version of Slidebars recently, and it has much more control.

The Android detection has gone, but you could still do this with your own script and check to see if a Slidebar is active.

```
var controller = new slidebars();

// Init
controller.init();

// Test for an active Slidebar
if ( controller.active( 'slidebar' ) ) {
  // A slidebar is active
}
```
