### ISSUE TITLE
Keep slidebars open on page load and then auto close on tablet/mobile

### ISSUE THREAD

**Issue by peterholmes** [adchsm/Slidebars#169]
Hi there,

I'm currently working on a project and using your slidebars plugin, great work by the way! However I've run into a little issue.

You closed an issue last year (https://github.com/adchsm/Slidebars/issues/108) regarding keeping the slidebars open on page load. I have followed the instructions on this and the jQuery works and they indeed do stay open, however the slidebars animate each time the page is loaded/refreshed. Is there any way to stop this? I guess it might be difficult if the slidebars are built with transform directly in the js file?

On top of this, how do I then get the slidebars to hide (and swap from active to not active) when the page hits mobile/tablet size? Would like the nav to always be open and then close itself specifically on certain screen sizes.

Cheers,
Peter.

**Comment by peterholmes** [comment]
Ok I may have solved this issue myself by adding .sb-slide, #sb-site, .sb-site-container, .sb-slidebar { transition:none!important; } to the media query. This stops the animation happening on the larger screen sizes. I've also included a window.resize function that closes the slide bar on smaller screens.

One problem, when the slidebars are closed (only after resizing browser smaller and not on page load), I can't get the open slidebar div to open them again on single click - it's wants two clicks. Assuming it's something to do with siteClose: true but can't quite work it out.

$(document).ready(function() {
	(function($) {
		var mySlidebars = new $.slidebars({
			siteClose: false
		});
		if($(window).width() > 724) {
			mySlidebars.slidebars.open('left');
		} else {
			mySlidebars.slidebars.close('left');
		}
		$(window).resize(function() {
			if($(window).width() > 724) {
				mySlidebars.slidebars.open('left');
			} else {
				mySlidebars.slidebars.close('left');
			}
		});
	}) (jQuery);
});

Cheers,
Peter.

**Comment by adchsm** [comment]
Hi Peter,

You could potentilaly load the new content in via ajax, this would stop the page from being reloaded entirely, so the Slidebar wouldn't close.

You could try something like the following using jQuey's [.load()](http://api.jquery.com/load/)

```javascript
$( 'body' ).on( 'click', 'a', function ( event ) {
  event.preventDefault();
  var link = $( this ).attr( 'href' );
  $( '#sb-site' ).load( link + ' #sb-site' );
} );
```
This would stop the default behavior of links, and replace the current `#sb-site` content with that of the new page.

You could also use JavaScript/jQuery to monitor the users screen size, and if it falls under a certain width, close them. You'd need to use [Slidebars API](http://plugins.adchsm.me/slidebars/usage.php#api) to control them.

```javascript
var yourVariable = new $.slidebars();

function slidebarsStatus() {
  var windowWidth = $( window ).width(),
  breakpoint = 768; // Or whatever your breakpoint is.

  if ( windowWidth > breakpoint && ( ! yourVariable.slidebars.active( 'left' ) || ! yourVariable.slidebars.active( 'right' ) ) ) {
    yourVariable.slidebars.open( 'left' ); // Right or left.
  } else if ( yourVariable.slidebars.active( 'left' ) || yourVariable.slidebars.active( 'right' ) ) {
    yourVariable.slidebars.close();
  }

}
slidebarsStatus();
$( window ).on( 'resize', slidebarsStatus ); 
```
This will initially run a window size check, and adds a resize check, which would open a Slidebar if over a certain width and if they are not already active.

Let me know if that helps,

Thanks, Adam

**Comment by peterholmes** [comment]
Thanks for your speedy reply Adam. I'll take a look, see what I can do and get back to you. Appreciate your help!

**Comment by kittles3069** [comment]
I don't know about Peter, but that worked perfectly for me. Thanks Adam.

**Comment by adchsm** [comment]
Great to hear it works, I'll close this for now then. Feel free to re-open if your still having problems :)

**Comment by uwood** [comment]
Hello Adam, 

Excellent plugin! It’s exactly what I’ve been looking for. Like Peter referenced in his original thread, I also needed an ‘auto-hide’ solution for “when the page hits mobile/tablet size”. The script you provided above appears to do the trick, however, I’m experiencing a bit of a glitch that I’m hoping you can help resolve in short order. Check out the link below for an example:  

http://uwjdesign.com/bench/slidebars/

Although the left Slidebar does close automatically when the browser is scaled down (horizontally) below the defined break-point, my left Slidebar content disappears intermittently while the site content (“sb-site”) remains in the .open state. Any suggestions you might have would be greatly appreciated. 

Thanks in advance for your time,

Ullysee
