### ISSUE TITLE
Unresponsive menu when using Owl Carousel

### ISSUE THREAD

**Issue by dmorda** [adchsm/Slidebars#171]
Hi Adam,

First off, awesome plugin. I got it up and running quickly and only recently discovered a minor issue when using Owl Carousel (http://owlgraphic.com/owlcarousel/), which I've been unable to track down.

When I visit a page that has an owl carousel every once in a while the menu will stop working. Here are the steps to reproduce:

1. From an iPhone, visit http://coastlife.wpengine.com/why-choose-us/
2. In the bottom right of the picture of the kid with the goggles on at the top, tap the arrow which will scroll the photo.
3. After tapping, try to use the menu again in the top right
4. It should do nothing if you tap on it, at least that's what it does for me.

I run into this issue on this page and any other page that is using Owl Carousel. I haven't been able to track down any javascript errors, but I'm hoping you can help me get this small wrinkle ironed out.

I'd gladly help you troubleshoot, just let me know what you need.

Thanks in advance.

**Comment by dmorda** [comment]
Actually, you can reproduce this in Safari too without using the iPhone simulator.

1. From Safari, visit http://coastlife.wpengine.com/why-choose-us/
2. Reduce the window width until the menu shows up
3. In the bottom right of the picture of the kid with the goggles on at the top, click the arrow which will scroll the photo.
4. After clicking the arrow, try to interact with the menu again
5. It should do nothing if you tap on it, at least that's what it does for me.

**Comment by dmorda** [comment]
For what it's worth, I was able to workaround the issue by editing the slidebars.js animation section.

I changed:
```javascript
selector.css('transform', 'translate(' + amount + ')'); // Apply the animation.
```
to this:
```javascript
selector.css('ms-transform', 'translate(' + amount + ')');
selector.css('-webkit-transform', 'translate(' + amount + ')');
selector.css('transform', 'translate(' + amount + ')');
```

For some reason once I interact with one of the Owl Carousels on the page, the translate call does not get applied to the selector.

**Comment by adchsm** [comment]
Hi Damon,

Yeah I'm aware of issues with Owl Slider and have no idea as to whats causing them. That's a great find with re-applying the translate css though. Any version of jQuery over 1.8 should automatically apply the vendor prefixes, but that's interesting to hear it provides a work around.

I'm not working on Slidebars just at the moment, but that will definitely help me with a fix in a future version.

I took a look at your site but was unable to replicate the problem though, however I was unable to use the Owl Carousel, in both Firefox and Safari, there were no arrows to control the slider (see attached picture.)

I'll keep this thread open and see if anyone else can help with the issues, otherwise i'll keep you updated here when I get a fix sorted.

Thanks, Adam

**Comment by adchsm** [comment]
![screen shot 2015-02-16 at 09 44 28](https://cloud.githubusercontent.com/assets/5276939/6209039/24736d84-b5c1-11e4-9094-192ab6dba975.png)

**Comment by dmorda** [comment]
Hi Adam,

It's good to hear you are already aware of the issue. I feel like it's a possible jQuery bug, but I couldn't tell for sure. I've setup a staging website where you can inspect the issue firsthand and I'll leave it up for a while while you take a peek.

http://coastlife.staging.wpengine.com/why-choose-us/

The arrows are actually there, but they were way to transparent. I darkened them up so you could see them easier and you can use any of the other carousels on the page to test too.

Let me know if you can reproduce the bug using the staging website when you get a chance.

Thanks!

**Comment by adchsm** [comment]
Hi Damon,

Yes I can replicate the issue now. Whats even stranger is sometimes it works ok.

If I load the page and open a Slidebar then click on the carousel arrows, the Slidebars continue to work. However if I click the carousel arrows before opening a Slidebar, they wont open at all.

It's definitely a Safari issue as it works perfectly in Firefox and Chrome. I thought it could be some sort of clashing -webkit- css, but looking at the Owl Carousel css sheet, there doesn't seem to be anything that would affect other elements.

So strange!

**Comment by breadadams** [comment]
Having the exact same issue, I have OwlCarousel set to autoscroll, so if the user doesn't select the toggle before it's made that first scroll, they can no longer open the slidebar. @dmorda that fix is working for me to, cheers!

**Comment by adchsm** [comment]
Thanks for letting me know that fix works, i'll look into this when I can.

**Comment by jenjika** [comment]
same issue. @dmorda that fix is working for me too! Thanks

**Comment by thesundayidiom** [comment]
I ran into the same issue. @dmorda that fix is working for me too! Thanks

**Comment by adchsm** [comment]
Thanks for confirming, I'll make sure I work this into the new version.

**Comment by adchsm** [comment]
Hi All,

The new upcoming version of Slidebars still has the same issue, however it is compatible with the newer 2.0 version of Owl Carousel.

You can get the beta of Slidebars from GitHub now, and the new Owl Carousel from here: http://www.owlcarousel.owlgraphic.com/

I'll close this issue now :)

Thanks,

Adam
