### ISSUE TITLE
On Show Event

### ISSUE THREAD

**Issue by DareDevil73** [adchsm/Slidebars#174]
Hi, I've urgently to calculate the outerHeight (by jQuery outerHeight method) of some sidebar inside items.

Unfortunately it's not possibile to calculate the outer height on an hidden object (http://stackoverflow.com/questions/4119078/jquery-outer-height-is-zero), so I want to ask you how I can trigger the sidebar show event.

Could you help me?

Thank you!!!

**Comment by adchsm** [comment]
Hi there,

You can use the Slidebars API. When initiating the plugin, create your own instance, and then you can use the API methods to open/close the Slidebars when you want.

http://plugins.adchsm.me/slidebars/usage.php#api

Let me know if that helps,

Adam

**Comment by DareDevil73** [comment]
Thak youm that's a good solution!

**Comment by adchsm** [comment]
There will be events that you can hook into at some point, but not currently.

Glad that helped :)

**Comment by DareDevil73** [comment]
Hi, unfortunately it's not enough.

The open method is asynchronous, I've to wait the inside elements ne visibile.

Could I hook the animation complete event?

Thank you again!

**Comment by DareDevil73** [comment]
Here is the solution, I hope :)

http://stackoverflow.com/questions/11284194/css3-transition-event-listener-with-jquery

**Comment by DareDevil73** [comment]
Hi again, the problem is not yet completely solved.

Is it possibile make the open API synchronous?

**Comment by adchsm** [comment]
I don't what that means I'm afraid.

**Comment by adchsm** [comment]
Have you tried getting the height of the object using .css()? I use that in the script to calculate the width/height when the object is hidden. Try this:

`var height = $( 'selector' ).css( 'height' );`

If you want to get a pixel-less value try:

`var height = parseInt( $( 'selector' ).css( 'height' ), 10 );`

Does that help?
