### ISSUE TITLE
Wordpress breaks Slidebar

### ISSUE THREAD

**Issue by RenegadeMonster** [adchsm/Slidebars#176]
I am having an issue with Slidebars and Wordpress.

I am developing a custom theme and when all the HTML is together Slidebars works correctly.  As soon as I do the bare minimum for a Wordpress theme, split the HTML file into 4 PHP files (header, index, sidebar and footer) with no further modifications other than adding the required hooks and when I load the theme into Wordpress Slidebars no longer works correctly.

What I experience is the page slides right when you open the left navigation menu and where the menu should be is just blank white space and the menu itself overlays the page as seen here:

![image](https://cloud.githubusercontent.com/assets/11876207/7074773/0a270ad4-decb-11e4-84a3-64484cfc4fac.png)

If the Wordpress Admin Bar is present it adds a black bar under Slidebars:

![image](https://cloud.githubusercontent.com/assets/11876207/7074847/9dd7cbe2-decb-11e4-8f4a-0b65e4a84a55.png)

For troubleshooting I have disabled the admin bar with a theme function and found that did nothing.

I have found Slidebars works as advertised when using the overlay style slide out menu.  It just doesn't work when the page slides right.

Adding the ".sb-style-push" class to my menu results in the menu sliding out from the left slightly delayed behind the page slide.  But the end result is the same overlay.  

I have tried using different versions of jQuery form 1.0 through the latest version.  

So far I am completely stumped and can't figure out why I can't get it to work with Wordpress.  

I pretty sure I can solve the Wordpress menu bar issue with a function that checks if the admin bar is present, and ad a div if it is pushing the Slidebar menu down.  

But I have no idea what to do about the issue with the menu not sliding out correctly.  

I was wondering if you have any tips as to what I can try to troubleshoot this issue and get the slide out with page slide right feature of Slidebars working right with my Wordpress Theme.  

Thanks

**Comment by RenegadeMonster** [comment]
After reading through the closed support threads, I tried to enqueue slidebars js and css to see if that solved my issue.  It made things even worse.  This is how Slidebar looks when enqueue with wp_enqueue_scripts from functions.php

![image](https://cloud.githubusercontent.com/assets/11876207/7092172/88f4897e-df7d-11e4-901e-8275d91df415.png)

Both Menu's now appear near the footer when opened.  

My sidebar.php is only my slidebars HTML instead of making a separate template bit.  


Any advice?

**Comment by adchsm** [comment]
Hey there,

Sorry to hear your having problems with WordPress. I've setup probably over 20+ WP sites with Slidebars, so i'll be able to help you figure it out.

You don't need to include jQuery, if your template has the `wp_head();` tag, WordPress will add it automatically. 

For the Slidebars markup, you'll be looking at something like:

header.php
```php
<div id="sb-site">
```

footer.php
```php
</div><!-- /#sb-site -->
<?php get_template_part( 'slidebars' );
```
slidebars.php
```php
<div class="sb-slidebar sb-left">
  <?php // Your menu or widget code or whatever else you want in here ?>
</div>

<div class="sb-slidebar sb-right">
  <?php // Your menu or widget code or whatever else you want in here ?>
</div>
```
You'll also as you said want to include slidebars js and css files by enqueuing, make sure that Slidebars js files wait for jQuery to be loaded first.

functions.php
```php
function enqueue_slidebars() {
  wp_enqueue_script(
    'slidebars',
    get_template_directory_uri() . '/path/to/slidebars.min.js',
    array( 'jquery' )
  );
  
  wp_enqueue_style(
    'slidebars',
    get_template_directory_uri() . '/path/to/slidebars.min.css'
  );
}

add_action( 'wp_enqueue_scripts', 'enqueue_slidebars' );
```

You'll want to add your initial script and enqueue that too, but i;m guessing you've already go that sorted.

That's pretty much the correct setup for the plugin. I'm not able to figure out whats going wrong from the screenshots, if you send me the url i'll be able to take a look at the markup and see if I can spot anything.

Let me know if that helps,

Thanks, Adam

**Comment by RenegadeMonster** [comment]
Thanks for the reply,

My markup looks similar to yours, except instead of having slidebars.php I just used Wordpress's sidebar.php since my sidebar is my right slidebars.

My sidebar.php looks like the following:

<div class="sb-slidebar sb-left">
        

        <nav>
            <?php if (function_exists(watic_left_menu())) watic_left_menu(); ?>        
        </nav>
        <?php if ( is_active_sidebar( 'sidebar-widget-area-left' ) ) { ?>
  
							<?php dynamic_sidebar( 'sidebar-widget-area-left' ); ?>
							
						<?php } ?>
    </div>

    <div class="sb-slidebar sb-right sb-style-overlay">
        
		<?php if ( is_active_sidebar( 'sidebar-widget-area-right' ) ) { ?>
  
							<?php dynamic_sidebar( 'sidebar-widget-area-right' ); ?>
							
						<?php } ?>
        
    </div>

sidebar.php is being called in from the footer.php file.  I don't think it matters that what file actually calls slidebars.

My enquere code looks like this:

function watic_scripts_styles() {

    wp_enqueue_script('jquery'); // just enqueue as its already registered 
    if ( is_singular() && comments_open() && get_option( 'thread_comments' ) )
        wp_enqueue_script( 'comment-reply' );

    /*   REGISTER ALL JS FOR SITE */
    wp_register_script('slidebars',get_stylesheet_directory_uri().'/js/slidebars.min.js', array( 'jquery' ));



    /*   REGISTER ALL CSS FOR SITE */
    wp_register_style('html5reset',get_stylesheet_directory_uri().'/css/html5reset.css');
    wp_register_style('bootstrap',get_stylesheet_directory_uri().'/css/bootstrap.min.css');
    wp_register_style('font-awesome',get_stylesheet_directory_uri().'/css/font-awesome.css');
    wp_register_style('slidebars_min',get_stylesheet_directory_uri().'/js/slidebars.min.css');
    wp_register_style('watic_theme',get_stylesheet_directory_uri().'/watic.css');



    /*   CALL ALL CSS AND SCRIPTS FOR SITE */
    wp_enqueue_script('slidebars');


    wp_enqueue_style( 'watic-style', get_stylesheet_uri(), array(), '1.0' );
    wp_enqueue_style('html5reset');
    wp_enqueue_style('bootstrap');
    wp_enqueue_style('font-awesome');
    wp_enqueue_style('slidebars_min');
    wp_enqueue_style('watic_theme');


}
add_action( 'wp_enqueue_scripts', 'watic_scripts_styles' );


I removed jQuery from my theme when I set up the wp_enqueure.  

Any idea as to what could be causing this issue based on the above information?  

Thanks

**Comment by adchsm** [comment]
Hey,

Hmm that seems to be included all ok, what about your header.php and footer.php files? Is the site container opened in the header and closed in the footer?

Is your sidebar.php file being called outside of the sb-site container?

Check your site with a tool like Tormus: http://www.tormus.com/tools/div_checker
Are all your divs closed?

If you don't want to publically reveal a url, you can email it to me at adam@adchsm.me.

Let me know,

Adam

**Comment by RenegadeMonster** [comment]
Thanks for the quick reply,

Yes, the site container is opened in the header file and closed in the footer file.  Sidebar.php is being called from outside of the sb-site container.

http://www.wearetheincrowdfans.com is the url of the site I am working on

Thanks for the tormus.com link, It is showing a missing closing div tag so looking into that right now.

**Comment by RenegadeMonster** [comment]
OK, found the missing closing div, somehow one got missed when splitting up the HTML.

Was rather tricky to find because the div map showed this one as closing but in the wrong spot and didn't give any suggestion as to where to look.

That seems to have fixed the issue.

Thanks for the help and I"m booking marking that link

**Comment by RenegadeMonster** [comment]
One more question though, when I have the widget of recent posts on the right slidebar, and view it on a iPhone there is overflow and the right sidebar then becomes scrollable which is good.  But it will not scroll all the way down.

It always leave the last 2 1/2 recent posts off the bottom of the screen.

Do you have any suggestions to fix that?

**Comment by adchsm** [comment]
Glad to hear you got it working :) you can fix that by adding a margin and padding to the slidebar, where 50px should be the height of your nav bar.

```css
.sb-style-overlay {
    margin-top: 50px;
    padding-bottom: 50px;
}
```

**Comment by RenegadeMonster** [comment]
Thanks, that did the trick!

**Comment by adchsm** [comment]
That's great news! I'll close this now, but feel free to comment again if you have any more problems.
