### ISSUE TITLE
how to show the sb-left content by default on large screen

### ISSUE THREAD

**Issue by LenWright** [adchsm/Slidebars#177]
Hi,

I'd like to display the content of my sb-left content whenever the window width is greater than say, 800px.

what's the best way to do that?

**Comment by adchsm** [comment]
Hi Len,

Slidebars is only used for off-canvas content, I wouldn't advise having a Slidebar open as a permanent feature - some of the main content area wouldn't be visible.

I'd just disable Slidebars on screens over 799px and use a CSS media query to display a sidebar in your main content area on screens over 800px.

```js
$.slidebars( {
  disableOver: 799
} );
```
