### ISSUE TITLE
Minimum height issue didnt solved

### ISSUE THREAD

**Issue by anahitaida** [adchsm/Slidebars#178]
Hi Adam,

I am very happy with your plugin but the minimum height issue didnt solved and it really worried me.
Please help me to fix this.

**Comment by adchsm** [comment]
Hi there,

Do you have a url I can see and what browser are you using?

I'll take a look but there wont be any fixes for the current version, as I'm developing 2.0, which doesn't actually set a min height.

Thanks, Adam

**Comment by anahitaida** [comment]
Yes have http://argentarius.ipoint.com.mt/platform/.You can see the blank
space.

Thanks!

**Comment by anahitaida** [comment]
Yes have *http://argentarius.ipoint.com.mt/platform/
<http://argentarius.ipoint.com.mt/platform/>* . You can see the blank space.

Thanks!

**Comment by adchsm** [comment]
This isn't happening because of Slidebars, take a look at these screen shots:

Slidebars is setting the min-height here to 734, which you can see highlighted:

![screen shot 2015-05-20 at 10 20 19](https://cloud.githubusercontent.com/assets/5276939/7721724/22c014bc-feda-11e4-88ef-a2a683e15b2b.png)

The problem is coming from &lt;div class="welcome_wrap_error"&gt; which has a 390px padding-bottom set.

![screen shot 2015-05-20 at 10 20 34](https://cloud.githubusercontent.com/assets/5276939/7721739/4031b488-feda-11e4-8430-66e7b5c7941c.png)

Which you can see here:

![screen shot 2015-05-20 at 10 20 26](https://cloud.githubusercontent.com/assets/5276939/7721741/45366c76-feda-11e4-898c-928d287bd8fa.png)

I hope that helps,

Thanks,

Adam

**Comment by anahitaida** [comment]
No you look into wrong link I had sent you again http://argentarius.ipoint.com.mt/platform/

**Comment by anahitaida** [comment]
When commnet the code of min-height  or setting it to 0 site now working properly.

**Comment by anahitaida** [comment]
It is really a bug, so please help me to fix

**Comment by adchsm** [comment]
It looks fine to me. What browser are you using?

Also try updating to the latest version, your running 0.10.1, 0.10.3 is out now.

**Comment by anahitaida** [comment]
Am using Chrome

**Comment by anahitaida** [comment]
when am opening it with Ispect element it is ok but when Inspect element closed you will see the result.

**Comment by adchsm** [comment]
Can you try updating to 0.10.3 please?

**Comment by anahitaida** [comment]
updated already

**Comment by anahitaida** [comment]
result is the same

**Comment by adchsm** [comment]
![screen shot 2015-05-20 at 10 42 57](https://cloud.githubusercontent.com/assets/5276939/7722065/0274f4b8-fedd-11e4-82ca-2fe351654c13.png)

**Comment by anahitaida** [comment]
refresh pls

**Comment by anahitaida** [comment]
http://argentarius.ipoint.com.mt/wp-content/themes/argentarius/js/slidebars.min.js

**Comment by anahitaida** [comment]
the css make sense?I updated only js

**Comment by adchsm** [comment]
http://argentarius.ipoint.com.mt/wp-content/themes/argentarius/css/slidebars.min.css

The CSS file is still showing 0.10.1

**Comment by anahitaida** [comment]
yes update css also, it make sense?

**Comment by adchsm** [comment]
You'll need to update the css file too, there are changes in that too.

**Comment by anahitaida** [comment]
one sec doing

**Comment by anahitaida** [comment]
changed but the same

**Comment by adchsm** [comment]
Hmm, I can't see the problem, can you send me a screenshot?

I see this:

![screen shot 2015-05-20 at 10 51 38](https://cloud.githubusercontent.com/assets/5276939/7722201/41e0d8f0-fede-11e4-9ac1-c3f2b819492e.png)

**Comment by anahitaida** [comment]
![platform argentarius](https://cloud.githubusercontent.com/assets/4764694/7722218/2ec8c5a0-feef-11e4-9ca4-afa7340cb907.png)
here it is

**Comment by anahitaida** [comment]
close Inspect element and resfresh, you will see the result

**Comment by adchsm** [comment]
Can you try putting your footer inside the sb-site container, it's meant to hold all of your content.

**Comment by anahitaida** [comment]
let me see

**Comment by anahitaida** [comment]
Ohhhhh issue solveddd!

**Comment by anahitaida** [comment]
You are genius.thank you very much!

**Comment by adchsm** [comment]
:) That's good to hear, glad you got it sorted!

**Comment by anahitaida** [comment]
You did it thx you very much!
