### ISSUE TITLE
Overlay layer with opacity over sb-site if navigation bar(ex: header) is fixed?

### ISSUE THREAD

**Issue by yukihariguchi** [adchsm/Slidebars#181]
Is it possible to add an overlay layer over "sb-site" when slidebar is open if navigation bar(ex: header) is fixed?

**Comment by adchsm** [comment]
Hi,

The Slidebars website has a fixed header and the right Slidebar is an overlay style, try it now:

http://plugins.adchsm.me/slidebars/

Is that what you mean?

Thanks,

Adam
