### ISSUE TITLE
Mobile menu button not working on iOS

### ISSUE THREAD

**Issue by johnpanz** [adchsm/Slidebars#183]
Can access the menu through my iphone 6, is this a known issue? Can't find any information on this anywhere? Not sure what the issue could be?

**Comment by adchsm** [comment]
Hey,

It's been tested on an iPhone 6 and works all ok, try visiting http://plugins.adchsm.me/slidebars/

Is this on your own implementation of Slidebars? Do you have a demo url I can see?

Thanks,

Adam
