### ISSUE TITLE
Fails when using a bootstrap modal

### ISSUE THREAD

**Issue by dimitriacosta** [adchsm/Slidebars#186]
Everytime I try to make a modal inside the class sb-site the screen turns a little black, as the background in the normal modal view, but it put the black screen in front of the modal, making unable to click or type anything, I need to reload the page to see it in a normal way

**Comment by adchsm** [comment]
Hey there,

Take a look at this, might help: http://plugins.adchsm.me/slidebars/issues/modal.php

Thanks,

Adam

**Comment by dimitriacosta** [comment]
Hey!
Sorry, I didn't saw it in the docs, thank you :+1: 
Thanks.

**Comment by adchsm** [comment]
No probs, hope you got it sorted :)
