### ISSUE TITLE
Strange behavior on IOS 8.4

### ISSUE THREAD

**Issue by semvgelooven** [adchsm/Slidebars#187]
Thank you for this great plugin! I love it. I have a problem though. On IOS 8.4 when you open the menu it works normally. But if you scroll down first and open the menu (fixed navbar) something strange happens and the menu and navbar go offscreen.Can you tell me what is causing this issue?

Thanks in advance!

**Comment by adchsm** [comment]
I don't think your using Slidebars, none of the usual markup is there :)

**Comment by semvgelooven** [comment]
Sorry I posted the wrong link! The website is not publicly visible yet. So i'll try and make a fiddle.

**Comment by adchsm** [comment]
Ahh ok, no problem. Does this only happen on iOS 8.4?

**Comment by semvgelooven** [comment]
hmm I think i figured it out, the overflow-x:hidden on the html, body element was missing. So that part is fixed. Only catch now is that the smooth ios scrolling is lost when scrolling the page.

**Comment by adchsm** [comment]
Ahh keep an eye out for the next version, it has the smooth scrolling already built in :)
