### ISSUE TITLE
Wordpress Admin Bar covers Slidebars top menu.

### ISSUE THREAD

**Issue by RenegadeMonster** [adchsm/Slidebars#191]
I have used Slidebars on a couple different Wordpress layouts I have made now.  One thing I have noticed is the admin bar covers the top navigation menu of slidebars.  It hasn't been an issue yet because I haven't allowed subscriber registration / commenting on the sites so visitors would never have this issue.  

However, I am currently working on a page where I will allow subscribers to register accounts and post content and when logged in the Wordpress admin bar appears and covers the navigation menu.  

I have found this example to work around this issue on the Wordpress support forums:

	    <?php 
  // Fix menu overlap bug..
  if ( is_admin_bar_showing() ) echo '<div style="min-height: 32px; position: absolute; right: 0;"></div>'; 
?>

However, this does not work because both slidebars and this create a fixed div occupying the same space.  If I take out the absolute positioning and place that code above slidebars it works when the page is at the top, but as soon as you start to scroll down the slidebars top navigation once again slides under the wordpress admin bar.

Have you ever encountered this problem and have a workaround for it?

Thanks

**Comment by RenegadeMonster** [comment]
Figured it out, was able to fix the issue by doing the following:

<nav class="navbar navbar-default navbar-fixed-top sb-slide" role="navigation" <?php if ( is_admin_bar_showing() ) echo 'style="margin-top: 32px !important;"' ?>>

**Comment by adchsm** [comment]
Hey,

If your using the `body_class()` tag, WordPress will add the class `admin-bar ` when it's showing, so you can just do a little CSS re-positioning.

```
body.admin-bar #your-navigation-bar {
    top: 46px;
}

body.admin-bar .sb-slidebar {
    padding-top: 46px;
}

@media ( min-width: 783px ) {
    body.admin-bar #your-navigation-bar {
        top: 32px;
    }

    body.admin-bar .sb-slidebar {
        padding-top: 32px;
    }
}

body.admin-bar #wpadminbar {
    position: fixed;
}
```

Replacing the `your-navigation-bar` id :)

I hope that helps,

Thanks,

Adam

**Comment by RenegadeMonster** [comment]
Just tried the method you posted.  While it pushes the top of the page down by 32 px when the admin bar is showing, the navbar is still under the admin bar.  

The fix I posted worked on page load, but once you hit the slidebars toggle the nav would jump up behind the admin bar.  

I'm going to play around with it some more to see if I can figure it out.

**Comment by adchsm** [comment]
The padding shouldn't make a difference to the Slidebars height as it has the `box-sizing: border-box;` property. Which browser are you experiencing the problem in?
