### ISSUE TITLE
Closing slidebars removes content of style attr on .sb-site-container

### ISSUE THREAD

**Issue by jornhenkes** [adchsm/Slidebars#192]
Hi, 

Thanks for making Slidebars, I've tried some of these plugins, yours works best so far! 

While working on two different website I found something that doesn't work for me. I'm using the menu in a WordPress website, where it's possible to set a background image in the admin. I'm adding this background image to the .sb-site-container in the style attribute, instead of the body. In that case I don't have to make background of  the .sb-site-container transparent. But after opening and closing the slidebars menu the background image is removed from the .sb.site-container's style attribute. I guess the content of the style attribute is removed completely when the menu gets closed. 

Is it possible to change this? That you only remove the style attributes that are needed for the menu to work, but keep the rest intact? 

Thanks, 
Jorn

**Comment by adchsm** [comment]
Hi Jorn,

With Slidebars 0.10.* it's not possible to change this, however no styles are removed like this in the new Slidebars 2. It might be a little work to migrate the markup and controls are totally different. It's still in beta, but it wont be long now.

Are you able to add the background image to class instead?

Thanks,

Adam

**Comment by jornhenkes** [comment]
Hi Adam, 

Thanks for the quick respons. I saw the beta already, so I might give that a try. I've added the image to the body again. Since I'm using a push menu, I don't see the menu. In this case it's fine. 

Any idea when version 2 will be released?

Thanks, 
Jorn

**Comment by adchsm** [comment]
Hi Jorn,

Probably within the next month, the framework itself is finished, I just need to complete testing, documentation and figure out new licensing options.

Just to let you know it does drop support for IE 8 and partially IE 9 (functional but no transitions) in favor of exclusive CSS animations, so that might be a deal breaker for you. If your only using it for mobiles/tablets though it'll be fine.

Thanks,

Adam

**Comment by adchsm** [comment]
Hi Jorn,

Just an update to let you know v2 was released and has removed this feature that was causing the issue for you!

Thanks,

Adam

**Comment by jornhenkes** [comment]
Hi Adam, 

Thanks for the update. I will try version 2 in my next project, thanks for all the work!
