### ISSUE TITLE
Slidebars will not work with Totomo Wordpress theme

### ISSUE THREAD

**Issue by RenegadeMonster** [adchsm/Slidebars#193]
I am using the Totomo Wordpress theme as a base theme to expand upon on a site I am creating.

I have checked and confirmed there are no unclosed div tags or extra closing div tags.

The issue I am having is the hamburger menu's don't appear and there is no way to slide open the right or left menus.  This is with the latest version of Slidebars.

I have also tested it on the latest 2.0 beta you have published as well.  In this case the above remains the same, but now the page becomes unscrollable.  I have tracked down that what ever is preventing the page from being able to scroll is located in slidebars.min.css.   

I have spent all day trying to figure this out and get it to work, and everything I have tried has resulted in the same result.

**Comment by adchsm** [comment]
Hey,

Slidebars doesn't actually contain any components - there is no navbar, the one on the website is used for illustrative purposes.

There is no styling for menus, lists, icons or widgets. It just provides a canvas and off-canvas areas with controls to open and close them. It was purposely designed this way, keeping file size to an absolute minimum and giving you the freedom to insert anything you want, in any style you want.

There are built in classes which trigger the Slidebars to open or close, which you can assign to your elements:
```
.sb-open-left
.sb-toggle-left
.sb-open-right
.sb-toggle-right
.sb-close
```

The markup is a little different for the new beta which may explain why the site locked up. The documentation for that is nearly ready alongside a new website which are both coming soon :)

I hope that helps to clarify a few things.

If your looking for a complete menu solution, you may be better off looking at [mmenu](http://mmenu.frebsite.nl/), since it has these pre-styled for you.

Thanks,

Adam

**Comment by RenegadeMonster** [comment]
Yes, I understand that it doesn't come with any components or styling.  

I started with the base code from your website, which creates an identical working representation in a html document.  However, when I use the code on the Totomo wordpress theme I just get the pick bar at the top with your nav links.  The Hamburger buttons / controls do not appear and there is no way to slide the off canvas content onto the page.

I am hoping to use slidebars, because I don't want a menu on the right and lift off canvas areas.  I want to be able to show stuff like the archives, popular tags, popular posts, tour dates and other stuff.  

I would like you to the page to take a look, but you wouldn't be able to view anything but a coming soon page without being logged into wordpress.  

All the slidebars scripts and css are properly enqueue into wordpress.

**Comment by RenegadeMonster** [comment]
Yes, I understand that it doesn't come with any components or styling.  

I started with the base code from your website, which creates an identical working representation in a html document.  However, when I use the code on the Totomo wordpress theme I just get the pick bar at the top with your nav links.  The Hamburger buttons / controls do not appear and there is no way to slide the off canvas content onto the page.

I am hoping to use slidebars, because I don't want a menu on the right and lift off canvas areas.  I want to be able to show stuff like the archives, popular tags, popular posts, tour dates and other stuff.  

I would like you to the page to take a look, but you wouldn't be able to view anything but a coming soon page without being logged into wordpress.  

All the slidebars scripts and css are properly enqueue into wordpress.

**Comment by RenegadeMonster** [comment]
Yes, I understand that it doesn't come with any components or styling.  

I started with the base code from your website, which creates an identical working representation in a html document.  However, when I use the code on the Totomo wordpress theme I just get the pick bar at the top with your nav links.  The Hamburger buttons / controls do not appear and there is no way to slide the off canvas content onto the page.

I am hoping to use slidebars, because I don't want a menu on the right and lift off canvas areas.  I want to be able to show stuff like the archives, popular tags, popular posts, tour dates and other stuff.  

I would like you to the page to take a look, but you wouldn't be able to view anything but a coming soon page without being logged into wordpress.  

All the slidebars scripts and css are properly enqueue into wordpress.

**Comment by adchsm** [comment]
Well the demo site uses Bootstrap too, have you included that?

I'm afraid that without a link there is very little I can do.

**Comment by RenegadeMonster** [comment]
Sorry about the double post, for some reason I didn't think it went through because when I hit comment I was just brought back to the write my post field.

Just opened up my site for a moment, http://www.againstthecurrent.rocks

**Comment by adchsm** [comment]
There is no styling on the toggles:

<img width="837" alt="screen shot 2015-08-06 at 15 49 44" src="https://cloud.githubusercontent.com/assets/5276939/9113092/de380cc6-3c52-11e5-9925-8435576c0756.png">

**Comment by RenegadeMonster** [comment]
hmm, your right...  Thanks

Looks like I overwrote my code with the styleless css file when switching back form 2.0.

Added it back in but something is still not quote right.  When you click on the controls instead of sliding the off canvas content out, the top menu jumps up and back under the wordpress admin bar.

**Comment by adchsm** [comment]
Hmm Slidebars is initializing and the clicks on the toggles are attempting to open the Slidebars. You can see the sb-active classes in the html and Slidebar element in the screenshot here:

<img width="751" alt="screen shot 2015-08-06 at 17 27 22" src="https://cloud.githubusercontent.com/assets/5276939/9115683/a2c9aa88-3c60-11e5-92af-24870875cd15.png">

I'm wondering if its a jQuery 2.* issue. Try switching to 1.10.* or 1.11.*.

If that doesn't help, are you using Owl Carousel? That can causes a similiar problem. Try disabling all of your plugins, and test it again. If that works, re-enable the plugins one by one testing in between and see which one is conflicting with it, we might be able to figure out whats causing it then.

Thanks,

Adam

**Comment by RenegadeMonster** [comment]
Just switched to 1.11.3 and I am having the same issue.

No, I am not using Owl Carousel yet, though I did plan on adding it in if I could get it to work with slidebars later on.

Going to start disabling plugins and I'll report back with my findings

**Comment by adchsm** [comment]
Owl Carousel 2 is compatible, but not the first version. Let me know how you get on with the other plugins.

**Comment by RenegadeMonster** [comment]
Yes, I read that and already on here when searching for similar issues to what I am experiencing and downloaded the latest version of Owl Carousel 2 to my mac to try out later.

I just disabled all my plugins, and I am experiencing the same issue still.  So it is not plugin related.

The Totomo theme does have it's on javascripts though, so I wonder if one of those could be at fault?

**Comment by adchsm** [comment]
Hmm i think I just got it to work - the Slidebar is active and has the translation applied, but the slidebars.css file is missing.

<img width="917" alt="screen shot 2015-08-06 at 17 55 47" src="https://cloud.githubusercontent.com/assets/5276939/9116392/7560e328-3c64-11e5-84d7-986f144e3569.png">

This one is not right:

<img width="860" alt="screen shot 2015-08-06 at 17 56 02" src="https://cloud.githubusercontent.com/assets/5276939/9116397/7785399c-3c64-11e5-9667-83146e4a8f20.png">

**Comment by RenegadeMonster** [comment]
hmm, what do you mean missing?

I can see that link for slidebars.css in the developer tools in chrome and view source, and when I click on it it loads the stylesheet.

**Comment by adchsm** [comment]
That is the stylesheet from the demo website, I'm referring to the actual Slidebars css:

https://github.com/adchsm/Slidebars/blob/master/dist/0.10.3/slidebars.css

**Comment by RenegadeMonster** [comment]
hmm, and funnything is that demo stylesheet worked for an other site I'm working on: http://www.wearetheincrowdfans.com as as well as some other sites.

I'll update that version of slidebars.css and see if that helps.

**Comment by RenegadeMonster** [comment]
Got it, thanks for you help.

I took slidebars.min.css off so it wasn't being  enqueue when I was trouble shooting the issue.   Placed that bag in and it works like a charm.

I'll clean up that demo stylesheet.  I think I left it that way because I used it to hold the style so it would be easier to upgrade slidebars to a newer version on an other project.

**Comment by adchsm** [comment]
Hey that's great news, glad you got it sorted :)
