### ISSUE TITLE
Re: Slidebars content disappears when auto close is triggered on tablet/mobile

### ISSUE THREAD

**Issue by uwood** [adchsm/Slidebars#201]
Hello Adam,

Excellent plugin! It’s exactly what I’ve been looking for. Like Peter referenced in thread [https://github.com/adchsm/Slidebars/issues/169], I also needed an ‘auto-hide’ solution for mobile/tablet devices. The following script you provided in the referenced thread appears to do the trick..., 

<pre><span class="pl-k">var</span> yourVariable <span class="pl-k">=</span> <span class="pl-k">new</span> $.slidebars();

<span class="pl-k">function</span> <span class="pl-en">slidebarsStatus</span>() {
  <span class="pl-k">var</span> windowWidth <span class="pl-k">=</span> $( <span class="pl-c1">window</span> ).<span class="pl-c1">width</span>(),
  breakpoint <span class="pl-k">=</span> <span class="pl-c1">768</span>; <span class="pl-c">// Or whatever your breakpoint is.</span>

  <span class="pl-k">if</span> ( windowWidth <span class="pl-k">&gt;</span> breakpoint <span class="pl-k">&amp;&amp;</span> ( <span class="pl-k">!</span> yourVariable.slidebars.active( <span class="pl-s"><span class="pl-pds">'</span>left<span class="pl-pds">'</span></span> ) <span class="pl-k">||</span> <span class="pl-k">!</span> yourVariable.slidebars.active( <span class="pl-s"><span class="pl-pds">'</span>right<span class="pl-pds">'</span></span> ) ) ) {
    yourVariable.slidebars.<span class="pl-c1">open</span>( <span class="pl-s"><span class="pl-pds">'</span>left<span class="pl-pds">'</span></span> ); <span class="pl-c">// Right or left.</span>
  } <span class="pl-k">else</span> <span class="pl-k">if</span> ( yourVariable.slidebars.active( <span class="pl-s"><span class="pl-pds">'</span>left<span class="pl-pds">'</span></span> ) <span class="pl-k">||</span> yourVariable.slidebars.active( <span class="pl-s"><span class="pl-pds">'</span>right<span class="pl-pds">'</span></span> ) ) {
    yourVariable.slidebars.<span class="pl-c1">close</span>();
  }

}
slidebarsStatus();
$( <span class="pl-c1">window</span> ).on( <span class="pl-s"><span class="pl-pds">'</span>resize<span class="pl-pds">'</span></span>, slidebarsStatus ); </pre>

...however, I’m experiencing a bit of a glitch that I’m hoping you can help resolve, or at least point me in the right direction. I've provided an example of the glitch via the following link:

http://uwjdesign.com/bench/slidebars/

Here's the problem..., Although the left Slidebar does close automatically when the browser is scaled down (horizontally) below the defined break-point, the Slidebar content disappears intermittently while the site content (“sb-site”) remains in the .open state. Any suggestions you might have would be greatly appreciated. Thanks in advance for your time.

Respectfully,

Ullysee

**Comment by adchsm** [comment]
Hey Ullysee,

So sorry for the extremely late reply, I was aware of this issue, and it should have been fixed with the latest version (2.x).

I'll close this for now, but feel free to open the issue again should you continue to experience any problems.

Thanks,

Adam
