### ISSUE TITLE
Menu 3 pixels over on first open

### ISSUE THREAD

**Issue by MonstaApps** [adchsm/Slidebars#203]
![untitled-2](https://cloud.githubusercontent.com/assets/10569474/10298761/ca882dca-6c3e-11e5-878a-a19d336e659e.png)
When you first open the menu it is 3 pixels too far to the right (see the screen shot from author's site). When you close it and re-open, it is correctly aligned. This is also happening on my install across Safari/Chrome/Firefox on iOS.

**Comment by Friksel** [comment]
I have it too. Menu was alright when it doesn't have the overlay style, but now it has overlay, no matter if it's a right or left slidebar, the first time the menu pushes too far in and leaves a gap

**Comment by Friksel** [comment]
Just fixed this here. It could be an ugly fix, but at least it works now without the ugly 3px gap right or left of the slidebar:

I found out jquery is not measuring the width of the slidebar well the first time, where it is setting the marginLeft or marginRight amount. The transform, wich is set later in code IS set to the correct amount of pixels.

So I just set the marginLeft or marginRight value again inside the transform() function to the same amount as the transform-value. Now it's always the right/same value and you don't have the 3px gap anymore.

Just replace the animate() function with this one in your code (using version 0.10.3):
The bold part is added to the code:

```
		function animate( object, amount, side ) {
			
			// Choose selectors depending on animation style.
			var selector;
			
			if ( object.hasClass( 'sb-style-push' ) ) {
				selector = $site.add( object ).add( $slide ); // Push - Animate site, Slidebar and user elements.
			} else if ( object.hasClass( 'sb-style-overlay' ) ) {
				selector = object; // Overlay - Animate Slidebar only.
			} else {
				selector = $site.add( $slide ); // Reveal - Animate site and user elements.
			}
			
			// Apply animation
			if ( animation === 'translate' ) {
				if ( amount === '0px' ) {
					removeAnimation();
				} else {
**                    // ----- TO FIX 3PX GAP BUG //
                    switch (side) {
                        case 'left':
                            selector.css( 'marginLeft', '-' + amount );
                            break;
                        case 'right':
                            selector.css( 'marginRight', amount );
                            break;
                    }
                    // ------- END FIX ---**
					selector.css( 'transform', 'translate( ' + amount + ' )' ); // Apply the animation.
				}

			} else if ( animation === 'side' ) {
				if ( amount === '0px' ) {
					removeAnimation();
				} else {
					if ( amount[0] === '-' ) amount = amount.substr( 1 ); // Remove the '-' from the passed amount for side animations.
					selector.css( side, '0px' ); // Add a 0 value so css transition works.
					setTimeout( function () { // Set a timeout to allow the 0 value to be applied above.
						selector.css( side, amount ); // Apply the animation.
					}, 1 );
				}

			} else if ( animation === 'jQuery' ) {
				if ( amount[0] === '-' ) amount = amount.substr( 1 ); // Remove the '-' from the passed amount for jQuery animations.
				var properties = {};
				properties[side] = amount;
				selector.stop().animate( properties, 400 ); // Stop any current jQuery animation before starting another.
			}
			
			// Remove animation
			function removeAnimation () {
				selector.removeAttr( 'style' );
				css();
			}
		}
```

**Comment by adchsm** [comment]
Hi @MonstaApps, @Friksel,

I've just released version 2 of Slidebars which should solve this problem. Check it out at [adchsm.com/slidebars](http://www.adchsm.com/slidebars/) and feel free to reopen the issue if the problem persists.

Thanks,

Adam

**Comment by MonstaApps** [comment]
Oh dear, the update broke my slider :-(

**Comment by adchsm** [comment]
Version 2 is a complete rewrite, it's not compatible with the first and has different markup and controls. You can find [usage instructions here](http://www.adchsm.com/slidebars/help/usage/), I hope that helps.
