### ISSUE TITLE
When using sb-style-push and scroll-lock

### ISSUE THREAD

**Issue by chrisbrooks** [adchsm/Slidebars#204]
Hi,

I'm using sb-style-push with scroll-lock and it doesn't account for the scroll bar so there is a gap on either the left or right depending on if your using a left/right menu. This only happens on the first time. Any idea?

Thanks

Thanks

**Comment by adchsm** [comment]
Hey Chris,

I believe this was an issue on Chrome only, which should have been fixed with the new version, feel free to raise this issue again if you continue to experience any problems.

Thanks,

Adam
