### ISSUE TITLE
Can't show right slider, native browser, Samsung Grand Prime (0.10.3)

### ISSUE THREAD

**Issue by a8568730** [adchsm/Slidebars#208]
Hi, thanks for this great work,
it saved our project. <3

### Problem
Samsung grand prime, Android 4.4.1, native browser 
When I click the `.sb-toggle-right` button, only show white and nothing

### Codepen
The usage template
jquery 1.10.2
slidebars 0.10.3 
http://codepen.io/sidk/pen/ojJjjZ

Before & after
![codepen_snap_before](https://cloud.githubusercontent.com/assets/6355592/11119836/28cef00c-8987-11e5-877d-0fe42507ea69.png) ![codepen_snap_after](https://cloud.githubusercontent.com/assets/6355592/11119835/28c70b58-8987-11e5-9c06-49080cc0c9ba.png)

### Update
slidebars 0.8  works fine, can toggle the right slider

**Comment by adchsm** [comment]
Glad you got it working :)
