### ISSUE TITLE
Slidebar from bottom

### ISSUE THREAD

**Issue by digitalgenossen** [adchsm/Slidebars#209]
Hi,

is it possible to use your plugin for opening a slidebar from the bottom of a page?

Thank you!

**Comment by adchsm** [comment]
Hi digitalgenossen,

I've just released version 2 of Slidebars which allows for multiple Sldiebars on any sides, including top and bottom. For more info, check out [adchsm.com/slidebars](http://www.adchsm.com/slidebars/) for more info and usage instructions.

Thanks,

Adam
