### ISSUE TITLE
multiple slidebars

### ISSUE THREAD

**Issue by carlosdv4** [adchsm/Slidebars#212]
Hi,

Merry xmas as well.

I'm wondering if is possible to have several slidebars, like 2 right bars and 2 or more left bars.
I couldn't find a way to add more than 2 slide bars. The code only accept 1 left bar and 1 right bar.

I'll appreciate all your help.
Regards.

**Comment by adchsm** [comment]
Hi carlosdv4,

I've just released version 2 of Slidebars which allows for multiple Sldiebars on any sides. For more info, check out [adchsm.com/slidebars](http://www.adchsm.com/slidebars/) for more info and usage instructions.

Thanks,

Adam
