### ISSUE TITLE
How to upgrade to AMD js?

### ISSUE THREAD

**Issue by beautylix** [adchsm/Slidebars#213]
The codes cannot work in AMD js, how to upgrade to AMD js? and then how to invoke it in other files?

**Comment by Viky-zhang** [comment]
@beautylix , Slidebars depends on jQuery, following requirjs configuration works for me .

```js
{
    paths: {
        jquery: 'jquery/dist/jquery',
        slidebars: 'Slidebars/dist/slidebars'
   },
   shim: {
        slidebars: {
            deps: ['jquery']
        }
    }
}
```

**Comment by adchsm** [comment]
Thanks for the help Viky-zhang.
