### ISSUE TITLE
Variables for the site and slidebar containers

### ISSUE THREAD

**Issue by Anke** [adchsm/Slidebars#214]
Hi Adam,

I just peeked at your extended slidebars, they do look promising! If I had a wish I'd like to be able to easily set the variables for the site and the slidebar containers, as content management systems usually have given ids and classes for their content blocks.

Or can I set vars for the containers in version 0.10.3? I'm not that fit with JS; if so, could you give me a hint?

Regards
Anke

**Comment by adchsm** [comment]
Hey @Anke 

I've just released Slidebars 2 today, check out [adchsm.com/slidebars](http://www.adchsm.com/slidebars/) for more info and usage instructions. Version 2 doesn't use any id's or classes, but it's own data-attribute. So you're free to use any of your own ids or classes on your containers.

I hope this helps.

Thanks,

Adam
