### ISSUE TITLE
spaghetti css in two css files 

### ISSUE THREAD

**Issue by getnathans** [adchsm/Slidebars#215]
You have two css files and both of them have similar css and they look really messy 
Very spaghetti css every where
You could have easily separate them and provide a maintainability

**Comment by adchsm** [comment]
I'm sorry I'm not quite sure what you mean? Are you referring to the slidebars.min.css? That's precisely the same as slidebars.css just minimized to reduce file size.

**Comment by getnathans** [comment]
Thanks for the reply
I was referring to your css files with duplicate styles.Both of the
style.css and slidebars.css have styles for same elements. For example you
have sb slide bar in both of the css files which makes very unmanageable
codes

**Comment by adchsm** [comment]
Yep that's how it is supposed to be slidebars.min.css is exactly the same as slidebars.css. You are only supposed to use one of them.

If you don't need to edit the script or are using it in a production site, use slidebars.min.css. If you need to edit it or are developing a site, use slidebars.css.

**Comment by getnathans** [comment]
You are talking about minified version of same css file.
But I am talking about two different css files you got under same css folder

**Comment by adchsm** [comment]
Which two files are you talking about then? Where are they located?

**Comment by getnathans** [comment]
Have a look at your source of http://plugins.adchsm.me/slidebars/
you can see

<link href='
http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic'
rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="
http://plugins.adchsm.me/slidebars/scripts/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="
http://plugins.adchsm.me/slidebars/scripts/slidebars/slidebars.min.css">
<link rel="stylesheet" href="http://plugins.adchsm.me/slidebars/style.css">

slidebars.min.css and style.css both have duplicated tags

I know slidebars as been minified but once you converted to normal file you
can still see ".sb-slidebar" all over the places and spread across both of
the files. You need lots of housekeeping to clean those css

**Comment by adchsm** [comment]
The style.css file isn't part of the plugin, that's why it is not included in the download anywhere. That is only used for styling the website. Slidebars doesn't come with any styling or components, which is why it is so lightweight.

**Comment by getnathans** [comment]
But my point is  when you  were doing your own website  you  hv used
style.css for styling. In that style.css and slidebars.css both of them
have same css elements. What  you could have done is adding parameters to
qjuery function.
Dont forget  that  people come in and check how you have done things and
wired things together before they hire you

**Comment by adchsm** [comment]
They are kept separate so it's easy to maintain.
