### ISSUE TITLE
eventHandler killing click events

### ISSUE THREAD

**Issue by TheWix** [adchsm/Slidebars#216]
Hey,

I think I may have found a bit of an issue here. I have a click event bound to an anchor that is also used to initiate a slide. The problem is when it is clicked my event never fires, but the slide one does. I traced it back to the eventHandler function that calls stopPropagation, preventDefault and kills the click events. When I comment these lines out everything work fine. This only seems to be the case with Chrome by the way.

**Comment by rsella** [comment]
Yeah, me too. 
In chrome (latest version, didn't test other browsers), clicks on a link in the slidebar are not fired. The script just close the panel. If i comment out the event handler function everything works properly.
Any ideas?

**Comment by rsella** [comment]
The solution of commenting the entire event handler method was bad. That breaks the "close on site click" feature. I solved by copy&past the event handler method and renaming it in eventHandlerFix(...). Then i changed the method call in the site click method to the previous event handler to the fix.
Finally i commented the original event handler. A bit hacky solution. but it works

**Comment by Ramsz** [comment]
Same issue, just got around installing this only to find out nothing happens when the WordPress menu links are clicked..... GREAT.

**Comment by adchsm** [comment]
The Slidebars no longer fires a stopPropagation or preventDefault actions, so this should no longer be a problem.

Thanks
