### ISSUE TITLE
Unable to Create .close() Event With Div That Encapsulates .open() Events

### ISSUE THREAD

**Issue by srthompson** [adchsm/Slidebars#217]
With the latest 2.0 Beta 14 build, it is not possible to create an on('click', .close() event with a div that encapsulates the on('click', .open() events.

**Comment by adchsm** [comment]
Hi there,

Without a demo I might not be able to figure out what's happening. Have you tried preventing the click event from propagating with [event.stopPropagation();](https://api.jquery.com/event.stoppropagation/)?

Thanks,

Adam
