### ISSUE TITLE
Transform not working iOS

### ISSUE THREAD

**Issue by aless673** [adchsm/Slidebars#219]
Hi, your plugin is not working on iOS 8.4 (any navigator) : the slider is not showing because transform is not interprated.

I used function iOS() to use jQuery for all iOS devices

http://stackoverflow.com/questions/9038625/detect-if-device-is-ios#answer-9039885

Add the test here

`if ( supportTransition && supportTransform && isiOS() ) { // Browser supports css transitions and transforms.` 

Now it works.

**Comment by adchsm** [comment]
I have no problems with Slidebars working on iOS 8 at all. Visit plugins.adchsm.com/slidebars on your device and test it.
