### ISSUE TITLE
Swipe don't work

### ISSUE THREAD

**Issue by gvieiradot** [adchsm/Slidebars#220]
I remember using Slidebars with swipe support.. That just don't work anymore..
I made a solution using https://github.com/mattbryson/TouchSwipe-Jquery-Plugin
I really appreciate the plugin.. hope you guys solve the problem!

Good Work!

**Comment by adchsm** [comment]
Hi there,

Slidebars hasn't ever had swipe support. However, you could bind touch events to Slidebars API to control them, but that doesn't come out of the box.

Thanks,

Adam
