### ISSUE TITLE
add lock settings after init

### ISSUE THREAD

**Issue by Viky-zhang** [adchsm/Slidebars#221]
I want to:
1. allow click page to auto close Slidebars.
2. sometimes I can press one button to lock Slidebars, so Slidebars will not auto close when I click page.

I don't want to modify Slidebars, because using bower. 

My currunt solution is (without modify source) [using jQuery](http://stackoverflow.com/a/2008622/2752670):
```js

// save click event to tmp var 
var tmp_slidebars_click_bind = $._data($('.sb-site-container')[0], "events").click;

// unbind click event
 $._data($('.sb-site-container')[0], "events").click = 0;

// if needed, rebind click event again
 $._data($('.sb-site-container')[0], "events").click = tmp_slidebars_click_bind ;

```

Can @adchsm add support for this feature directly in source ?

**Comment by adchsm** [comment]
The new version of Slidebars doesn't have any lock settings, but is locked by default. I'll close this, but please raise a new issue if you continue to experience any problems.
