### ISSUE TITLE
Slidebars works fine on Chrome and Safari but does not work at all on Firefox?

### ISSUE THREAD

**Issue by Jody6** [adchsm/Slidebars#223]
Hi. Slidebars is a really cool pluggin thanks. It is working fine in Chrome and Safari but does not work at all in Firefox. Do you know why? My code is below. `<!DOCTYPE html>
<html lang="en">

<head>

    
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <meta content="ie=edge" http-equiv="x-ua-compatible">

    
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" rel="stylesheet">

    
    <link rel="stylesheet" href="stylesV5.css">

    
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" rel="stylesheet">

    
    <link href="ionicons.css" rel="stylesheet">

    
    <link rel="stylesheet" href="slidebars/slidebars.css">
        
    <title></title>

</head>

<body>

<div id="sb-site" class>
          
    
    
    <section class="cover">
      <div id="cover-caption">
        <div class="container hero-container"> 

          
          <div class="navbar-wrapper">

            
            <nav class="navbar">
              <a class="navbar-brand" href="#"><img class="sameBoatLogoColor" src="images/sameBoatLogoColor.png"></a>
        
                                                                              
              <form class="form-inline content-page-menu-buttons">                                        
                  <button class="btn btn-success-outline disappear-btn" type="submit">SIGN UP</button> 
                  <button class="btn btn-success-outline disappear-btn" type="submit">LOG IN</button>
                  <button class="nav-button"><i class="ion-navicon sb-toggle-right"></i></button>
              </form>
            </nav>
          </div>

          
          <div class="col-sm-10 col-sm-offset-1 heroText">
            <h1>No one knows what it’s like<br> quite like someone in the same boat.</h1>
            <p>Welcome to SameBoat – where people with shared experiences find their way together.</p>

            
            <form action="" class="form-inline">
              <div class="input-group">         
                    <input type="text" class="form-control form-control-lg id-like-to-speak" placeholder="I'd like to speak to someone in the same boat about...">
                    <input type="text" class="form-control form-control-lg search" placeholder="Type your topic...">
                    <span class="input-group-btn">
                      <button class="btn lets-chat-btn" type="button">LET'S CHAT</button>
                    </span>
              </div> 
            </form>
          </div>

        </div>
      </div>
    </section>
  

    
    <section>
        <div class="container">
          <div class="Top-trending-topics">
            <h3>TOP TRENDING TOPICS</h3>
          </div>
        </div>
    </section>

   
    
    <section>
      <div class="section-content">
        <div class="container color-box-container">

          
        <div class="grid">
          <div class="grid-sizer"></div>

            

            
            <div class="grid-item blue">
              <p>Posted - 20 June</p>
              <h2>Maybe I'm already in the deep end.</h2>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              

              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>

            
            <div class="grid-item grid-item--width2 grid-item--height2 cream">
              <p>Posted - 20 June</p> 
              <h4>Maybe I'm already in the deep end.</h4>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>

            
            <div class="grid-item grid-item--width2 grid-item--height2 sea-green">
              <p>Posted - 20 June</p>
              <h4>Maybe I'm already in the deep end.</h4>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>
            
            
            <div class="grid-item green">
              <p>Posted - 20 June</p>
              <h2>Maybe I'm already in the deep end.</h2>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>
            
            
            <div class="grid-item grid-item--width2 grid-item--height2 green">
              <p>Posted - 20 June</p>
              <h4>Maybe I'm already in the deep end.</h4>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>
            
            
            <div class="grid-item grid-item--width2 grid-item--height2 aqua">
              <p>Posted - 20 June</p>
              <h4>Maybe I'm already in the deep end.</h4>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>

          </div>

          <div class="gridBottom">
            <div class="grid-sizerBottom"></div>

            
                      
            
            <div class="grid-itemBottom grid-item--width3 grid-item--height3 cream">
              <p>Posted - 20 June</p>
              <h3>Maybe I'm already in the deep end.</h3>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>
            
            
            <div class="grid-itemBottom grid-item--width3 grid-item--height3 blue">
              <p>Posted - 20 June</p>
              <h3>Maybe I'm already in the deep end.</h3>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>
            
            
            <div class="grid-itemBottom grid-item--width3 grid-item--height3 aqua">
              <p>Posted - 20 June</p>
              <h3>Maybe I'm already in the deep end.</h3>
              <div class="circle circle-home-page"><i class="fa fa-user" aria-hidden="true"></i><span class="info">Anonymous</span></div>
              <div class="eyes">
                <i class="fa fa-heart-o" aria-hidden="true"></i> 25
                <i class="fa fa-eye" aria-hidden="true"></i> 100
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>

    
    <section>
      <div class="load-more-button-div">
        <button class="load-more-button"><p>LOAD MORE</p></button>
      </div>
    </section>

</div>

      
    <div class="sb-slidebar sb-right narrow-screen-menu">
        <ul class="menu sb-close">
          <li><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Services</a></li> 
          <li><a href="#">Contact</a></li>
          <li class="narrow-only"><a href="#">Sign Up</a></li>  
          <li class="narrow-only"><a href="#">Log In</a></li>
        </ul>
    </div>

     
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script> 

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>

    
    <script src="https://npmcdn.com/masonry-layout@4.0/dist/masonry.pkgd.js"></script>

      
    <script src="script.js"></script>

    
    <script src="scriptV4.js"></script>

    
    <script src="slidebars/slidebars.js"></script>
    <script>
        (function($) {
            $(document).ready(function() {
                $.slidebars();
            });
        }) (jQuery);
    </script>
</body>
</html>

`

**Comment by adchsm** [comment]
Hi there,

I can't entirely see your pages code, half of it's rendered.

I've just released a new version of Slidebars and I'm discontinuing support for older versions. Try upgrading to the latest version and if you're still having issues, feel free to re-open an issue here.

Many thanks,

Adam

**Comment by Jody6** [comment]
Hi Adam

Ok thank you for getting back to me.

I will try your new one.

I like your Sidebars :)

Jody
