### ISSUE TITLE
Does not work on mobile devices

### ISSUE THREAD

**Issue by ayumihamsaki** [adchsm/Slidebars#224]
When you install this script and run and test it on a mobile device such as an ipad and you rotate the device from Portrait to Landscape and vice-versa you will get a huge white area under the footer. Even the official test web page does this: http://plugins.adchsm.me/slidebars/

So basically works all fine until people start rotating their mobile devices.

**Comment by ayumihamsaki** [comment]
Sorry this is the same as Issue number: 83

White Space at the bottom of the website,. Seems to be problem with IOS devices, does not matter what type of browser you use in an IOS device. ~ Going to test out version 2 of this lib.

**Comment by adchsm** [comment]
Hi there,

Sorry to hear you're having problems.

Both v1 and v2 worked absolutely fine with rotations. Version 2 is quite a different setup from the first, you can't just drop it in. I've just released the new site today where you can find usage instructions.

Take a look at adchsm.com/slidebars and let me know if you're still experiencing any issues.

Thanks,

Adam
