### ISSUE TITLE
If user clicks on canvas=container to close slidebar they can accidentally click a link - block interaction with what's inside canvas=content when a slidebar is open

### ISSUE THREAD

**Issue by kubik101** [adchsm/Slidebars#226]
I have a scenario I would like to avoid.

As a user we often click anywhere on the canvas=container to close the side menu if open.

Within the example (see link) there is a header slider that has a link on each slide. 
The chance is high that a user will hit a link when clicking anywhere on canvas=container to close the slidebar.

http://goo.gl/7yBQdx

Can you add the ability in to Slidebar to block interaction with what's inside canvas=content when a slidebar is open?

**Comment by adchsm** [comment]
Yep that's possible. I'd add a class to the container based on opening or closing events. Then filter a document click by that class to close it, preventing the default action.

```
// Controller
var controller = new slidebars();
controller.init();

// Close any
$( document ).on( 'click', '.js-close-any', function ( event ) {
  if ( controller.getActiveSlidebar() ) {
    event.preventDefault();
    event.stopPropagation();
    controller.close();
  }
} );

// Add close class to canvas container when Slidebar is opened
$( controller.events ).on( 'opening', function ( event ) {
  $( '[canvas]' ).addClass( 'js-close-any' );
} );

// Add close class to canvas container when Slidebar is opened
$( controller.events ).on( 'closing', function ( event ) {
  $( '[canvas]' ).removeClass( 'js-close-any' );
} );
```

**Comment by kubik101** [comment]
Excellent, thanks so much, that did the trick.

I noticed that having the original close any code (see below) from your scripts.js file along with the above code causes the new code not to work.

Is what you provided above meant to replace the below?
Or is some function in the below code we need to retain?

`// Close any
$( controller.events ).on( 'opened', function () {
	$( '[canvas="container"]' ).addClass( 'js-close-any-slidebar' );
} );

$( controller.events ).on( 'closed', function () {
	$( '[canvas="container"]' ).removeClass( 'js-close-any-slidebar' );
} );

$( 'body' ).on( 'click', '.js-close-any-slidebar', function ( event ) {
	event.stopPropagation();
	controller.close();
} );`

**Comment by adchsm** [comment]
It was meant to replace it. The class name had also changed too from `.js-close-any-slidebar` to `.js-close-any`

**Comment by kubik101** [comment]
Thanks mate.

**Comment by jacklinwood** [comment]
I used the above solution which worked well for desktop but not for mobile.

I can see that the slidebar on the homepage of the website works well on mobile?

**Comment by alexpanait** [comment]
@jacklinwood we're you able to find a fix for this?
