### ISSUE TITLE
Markup don't validate: data-attrbutes instead of own attributes

### ISSUE THREAD

**Issue by macgamper** [adchsm/Slidebars#231]
The HTML-markup with the new attrbutes (canvas, off-canvas, …) won't validate anymore:
https://html5.validator.nu/?doc=http://www.adchsm.com/slidebars

Is there a config to replace this new attributes with standard compliant attributes like "data-canvas" or with classes like in the old version?

**Comment by adchsm** [comment]
Yep I guess you could perform a find and replace across all `canvas` and `off-canvas` to `data-canvas` and `data-off-canvas` selectors in the CSS and JS. I won't be creating this version however.

**Comment by vincoweb** [comment]
It is not good idea change js and I use CDNJS. Pls change library

**Comment by DenisLabrecque** [comment]
This needs to be fixed.

**Comment by JoryHogeveen** [comment]
@DenisLabrecque Fixed on my fork: https://github.com/JoryHogeveen/Slidebars/pull/3

Version release: https://github.com/JoryHogeveen/Slidebars/releases/tag/2.1
