### ISSUE TITLE
affix or fixed problem

### ISSUE THREAD

**Issue by i-m-d** [adchsm/Slidebars#234]
Hello,

 First of all thank you for SlideBars !!!!

 I am using SlideBars in my new design i am working right now, but i have a problem with affix or fixed DIV.
 I want to make a fixed sidebar menu but this sidebar menu it is not fix, scroll up/down with the text/page.

 Two different examples:

 1) http://test.imd.guru/redes/index.html
    code taken from: http://bootsnipp.com/snippets/featured/bootstrap-docs-sidebar

 2) http://test.imd.guru/retro/index.html 
    code taken from: http://www.codingeverything.com/2014/02/BootstrapDocsSideBar.html

 Please sorry for my bad English and i am not an expert in CSS/JS.

 Thank you for reading.

**Comment by adchsm** [comment]
Hi there,

You can find info and example for this in the Help Center at https://www.adchsm.com/slidebars/help/advanced-usage/elements-with-fixed-positions/

I hope that helps,

Thanks,

Adam

**Comment by i-m-d** [comment]
Thank you Adam.... i already saw that but no help me or i was not able to do it work....
