### ISSUE TITLE
$ is not a function

### ISSUE THREAD

**Issue by erichomanchuk** [adchsm/Slidebars#238]
Is there a reason why you stopped encapsulating the slidebars.js with the jQuery object. If another script declares jQuery.noConflict(); the $ will no longer be defined which stops slidebars from working.

**Comment by erichomanchuk** [comment]
I see actually that that would cause slidebars to break as it not written as a plugin.

**Comment by JoryHogeveen** [comment]
Same problem here.
I'm trying to merge v2.0.2 info the off canvas plugin for WordPress, but the new version won't work since $ isn't defined globally.

**Comment by JoryHogeveen** [comment]
@erichomanchuk 
Quick workaround it to pass jQuery as a variable into the function:

`var slidebars = function ($) {` (Line 11 at slidebars.js)

And declare slidebars as so:
```js
(function($) {
    var slidebars_controller = new slidebars( $ );
    slidebars_controller.init();
}) (jQuery);
```

**Comment by JoryHogeveen** [comment]
@erichomanchuk 
PR #240 fixes this!

**Comment by erichomanchuk** [comment]
@JoryHogeveen 
Thank you.

**Comment by JoryHogeveen** [comment]
NP!
But I'd keep this issue opened untill the PR is merged.
