### ISSUE TITLE
More than one Slidebar content/same side

### ISSUE THREAD

**Issue by cezaraugusto** [adchsm/Slidebars#27]
Hi Adam,

Is it possible to have two different contents on the same slidebar area? I mean, supposing I want to display X content selecting the X button and another content if Y button is selected, all on the right slidebar. It would be great.

**Comment by cezaraugusto** [comment]
Great, thanks!!

I'll try to insert the content of bootstrap navigation inside slidebars on small screens, and maybe the shopping cart too. Lots of plans

**Comment by blaaaaaaaam** [comment]
Hi Adam, the script that you posted in your reply has been removed. If this is because the script was outdated is it possible to do this feature in the current version of slidebars?

**Comment by adchsm** [comment]
Hey, 

I'm not sure what was in that reply, it was quite long ago :(

However, it is possible to have multiple Slidebars on the same side with the new Slidebars. The beta is available to download here at GitHub and you can find some usage instructions at: https://adchsm.zendesk.com/hc/en-us/categories/200490081-Slidebars

Some of the docs are still being written, but the general processes of adding and controlling are up! The setup is very different, but it permits top and bottom and unlimited amount of Slidebars on any sides, so its a pretty good trade off!

I hope that helps,

Adam
