### ISSUE TITLE
Scroll Locked But...

### ISSUE THREAD

**Issue by sadeghbarati** [adchsm/Slidebars#279]
Slidebars options works right but some thing wroung with scroll lock
here the photo 
![untitled](https://cloud.githubusercontent.com/assets/17789047/24610219/0034bc34-1893-11e7-91da-e74b9e82fe6e.png)

a little space apear after i add scrollLock:true in slidbars options
help pls

**Comment by tucq88** [comment]
I think it's just CSS issue, you could create an overwrite for it?

**Comment by JoryHogeveen** [comment]
I believe scroll lock was an 0.x feature that doesn't exists in 2.x anymore. What code are you using to lock the scroll bar?
