### ISSUE TITLE
jQuery.fn.resize() event shorthand is deprecated

### ISSUE THREAD

**Issue by DenisLabrecque** [adchsm/Slidebars#306]
Not up to date with the newest version of jQuery 3.5.1

**Comment by JoryHogeveen** [comment]
Where do you see this shorthand version used?

**Comment by DenisLabrecque** [comment]
It happens in our code when what I assume is the constructor gets called `$.slidebars()`. Let me check with the uncompressed version.

**Comment by DenisLabrecque** [comment]
Very sorry for the false alarm. Our version is clearly slidebars 0.10.3. I'll have to figure out how to migrate.
