### ISSUE TITLE
Calculating scroll position

### ISSUE THREAD

**Issue by jonastebbe** [adchsm/Slidebars#39]
When using slidebars, plugins like wow.js (http://mynameismatthieu.com/WOW/) and other plugins calculating scroll position won't work.
Afaik the issue occurs, because you scroll the #sb-site DIV instead of the body.
Any suggestions?

**Comment by andrewtibbetts** [comment]
I was having this issue. I found it was caused by setting `height: 100%;` for `html, body` after slidebars' css had loaded.
