### ISSUE TITLE
Add Callback option

### ISSUE THREAD

**Issue by jmartsch** [adchsm/Slidebars#66]
Please add an option for a callbacks. I have a one-page website with smooth scrolling.
When i click a link in slidebar the slidebar closes but simultaneous scrolls down. I want to close the slidebar first, and then do the scrolling. Could be easy:
```
mySlidebars.close(function(){
// do this
});
```
Please also add an option for callbacks on slidebar.open()

**Comment by hakpersson** [comment]
I´m having trouble getting this to work in conjunction with an animated icon. Could someone please point me in the right direction? Getting it to work with "button -open/close" is straight forward, but looking for a solution that also accounts for "siteClose: true". So icon animates/changes in all cases...

**Comment by adchsm** [comment]
The `html` element has class `sb-active` when any Slidebar is open, so if your animating through css only, you could hook into that.

```css
.your-icon {
}

html.sb-active .your-icon {
}
```

**Comment by hakpersson** [comment]
Thank you for quick reply @adchsm ! Simple and effective tip for css-animation.

**Comment by adchsm** [comment]
Hey,

After a long time I ave finally got around to developing a new version of Slidebars.

Callbacks have been added :)

Thanks,

Adam

**Comment by jmartsch** [comment]
1 year later ^^ But nice. I´ll take a look at it.

**Comment by adchsm** [comment]
Haha yeah I know :)

I had some other projects that required my attention, and I feel I needed to improve my own coding skills before I could make Slidebars into the plugin I wanted it to be.

Anyway, now you can also add unlimited instances and top and bottom ones too :)

I'm still writing up the docs but you can find some info on callbacks here: https://adchsm.zendesk.com/hc/en-us/categories/200490081-Slidebars

It's the first beta, so any feedback would be really appreciated!
