### ISSUE TITLE
Slidebar scrolling on mobile

### ISSUE THREAD

**Issue by svanetten1976** [adchsm/Slidebars#83]
First of all, thanks for writing a terrific plugin. Not sure if this is an issue with Slidebars or something to do with related CSS/JS on this site I'm building. This is a responsive design using Slidebars for the primary nav: http://drlathian.com/clients/dusa/levulan/demo/index.html  -- Slidebars works great but the single issue is that on mobile, the slidebar doesn't scroll properly, it just gets stuck at the top of the viewport so some content at the bottom of the slidebar is just hidden in landscape mode. Thanks, Steve

**Comment by darylknight** [comment]
I get the problem of white space at the bottom of the menu too - is there a fix for it?

**Comment by adchsm** [comment]
I believe this should be fixed with the new version 2.0. If you want to give it a shot and let me knowI'd really appreciate it.

Your markup and initiation has to change though, and is documented here: https://adchsm.zendesk.com/hc/en-us/categories/200490081-Slidebars

**Comment by darylknight** [comment]
Hey Adam, sorry for the delay on this one. The current site I'm using it on works with the fix you provided, but I'm building another site right now with it, so I'll integrate it with version 2 and let you know if I run in to any problems - thanks!

**Comment by adchsm** [comment]
Ok sounds good, looking forward to hearing how it goes :)
