### ISSUE TITLE
How to make slidebar links act like normal links

### ISSUE THREAD

**Issue by barbmc** [adchsm/Slidebars#89]
I'm using version 0.8.2 and I want the menu links in the left sidebar to act like normal links so that the sidebar won't close and the menu won't toggle closed and also so that any javascript click events will trigger.

Is there a way to achieve this? I have tried adding class sb-disable-close, but that didn't do anything.

**Comment by adamjw3** [comment]
This still doesn't work for me in ios iphone 5 and ipad

https://github.com/adchsm/Slidebars/issues/218
