### ISSUE TITLE
Add events

### ISSUE THREAD

**Issue by ewal** [adchsm/Slidebars#90]
Love the plugin. Would love it event more if it had events to listen on like: open, opened, close, closed etc.

**Comment by foysalit** [comment]
#170 Submitted a pull request with a couple of the events proposed. init and active events are missing.

**Comment by adchsm** [comment]
Hey there,

After a long break, I have developed a new version of Slidebars, with lots of events now added :)

It's still in beta but you can see some docs here: https://adchsm.zendesk.com/hc/en-us/categories/200490081-Slidebars

Thanks,

Adam

**Comment by adchsm** [comment]
The CSS file is still showing 0.10.1

**Comment by Alex100dre** [comment]
Hi, nice !
When would it be available ?

**Comment by adchsm** [comment]
The beta is available now here at GitHub, it's stable - but needs a little tweaking and testing.
